### ISSUE TITLE
Batching rule for 'mhlo_apply' 

### ISSUE THREAD

**Issue by Sruthi-sk** [google-deepmind/tf2jax#196]
Hi, 
Could you help me get this working with vmap?
I'm referring to this code: [tf2jax/experimental/mhlo.py#L46](https://github.com/google-deepmind/tf2jax/blob/63b20214a1b8b2c9cb854f0ec3260739a5b82391/tf2jax/experimental/mhlo.py#L46)

I encountered the following error in a code which uses this library: NotImplementedError: Batching rule for 'mhlo_apply' not implemented

**Comment by shaobohou** [comment]
Unfortunately, there is no general batching rule for mhlo_apply, which can contain arbitrary mhlo/jax program. 

You may be able to implement something that naively iterate over the batched dimension and invoke the primitive rule for each element. But there wouldn't be much performance benefit.

If you are able to rewrite your code to use a polymorphic batch dimension, that might work better. https://github.com/google/jax/blob/main/jax/experimental/jax2tf/README.md#shape-polymorphic-conversion

**Comment by Sruthi-sk** [comment]
Thank you, I'll check this out!
