### ISSUE TITLE
[Bug report] Issue in conversion for squeeze op

### ISSUE THREAD

**Issue by aboubezari** [google-deepmind/tf2jax#226]
The squeeze operator is not converted to JAX properly when the `axis` argument is `None`. This is converted to an empty list in JAX, which does nothing. It should propagate the `None` value and squeeze all value 1 axes.

Offending code: https://github.com/google-deepmind/tf2jax/blob/main/tf2jax/_src/ops.py#L1882-L1888

**Comment by shaobohou** [comment]
Thanks for the report, could you add a code snippet that reproduces the bug?

**Comment by shaobohou** [comment]
Thanks, what is the TF, JAX and tf2jax versions you are using?

**Comment by aboubezari** [comment]
> Thanks, what is the TF, JAX and tf2jax versions you are using?

Our versions are:
```
tensorflow==2.12
jax==0.4.23
tf2jax==0.3.5
```

**Comment by shaobohou** [comment]
Ah, okay, I can't reproduce this on 0.3.6, can you upgrade?

**Comment by aboubezari** [comment]
Will do. Thanks!
